import streamlit as st
import pandas as pd
import mysql.connector
import plotly.express as px

st.set_page_config(page_title="Bus Delay Dashboard", layout="wide")

DB_CONFIG = {
    "host": "localhost",
    "user": "student",
    "password": "1234",
    "database": "autobusu_parkas"
}

@st.cache_data
def load_data():
    conn = mysql.connector.connect(**DB_CONFIG)

    routes = pd.read_sql("SELECT * FROM routes", conn)
    timetables = pd.read_sql("SELECT * FROM timetables", conn)
    stops = pd.read_sql("SELECT * FROM stops", conn)
    stopping_points = pd.read_sql("SELECT * FROM stopping_points", conn)

    try:
        predicted_arrivals = pd.read_sql("SELECT * FROM predicted_arrivals", conn)
    except:
        predicted_arrivals = pd.DataFrame()

    conn.close()
    return routes, timetables, stops, stopping_points, predicted_arrivals


routes, timetables, stops, stopping_points, predicted_arrivals = load_data()

st.title("Bus Timetable and Delay Visualization Platform")

st.markdown("This dashboard visualizes internal bus data and predicted delays generated by the Homework 2 workflow.")

# Sidebar filters
st.sidebar.header("Filters")

selected_stop = "All"
min_delay = 0

if not predicted_arrivals.empty:
    stop_options = ["All"] + sorted(predicted_arrivals["stop_name"].dropna().unique().tolist())
    selected_stop = st.sidebar.selectbox("Select stop", stop_options)
    min_delay = st.sidebar.slider("Minimum delay (minutes)", 0, 60, 0)

# Section 1: Database overview
st.subheader("1. Database Overview")

col1, col2, col3, col4, col5 = st.columns(5)
col1.metric("Routes", len(routes))
col2.metric("Timetables", len(timetables))
col3.metric("Stops", len(stops))
col4.metric("Stopping Points", len(stopping_points))
col5.metric("Predicted Arrivals", len(predicted_arrivals))

# Section 2: Main data tables
st.subheader("2. Imported System Data")

tab1, tab2, tab3, tab4, tab5 = st.tabs([
    "Routes", "Timetables", "Stops", "Stopping Points", "Predicted Arrivals"
])

with tab1:
    st.dataframe(routes, use_container_width=True)

with tab2:
    st.dataframe(timetables, use_container_width=True)

with tab3:
    st.dataframe(stops, use_container_width=True)

with tab4:
    st.dataframe(stopping_points, use_container_width=True)

with tab5:
    if predicted_arrivals.empty:
        st.warning("No predicted_arrivals table found or no data available.")
    else:
        st.dataframe(predicted_arrivals, use_container_width=True)

# Section 3: Interactive filtering
st.subheader("3. Interactive Delay Analysis")

if predicted_arrivals.empty:
    st.info("Predicted arrivals are not available yet. Run Homework 2 workflow first.")
else:
    filtered_df = predicted_arrivals.copy()

    if selected_stop != "All":
        filtered_df = filtered_df[filtered_df["stop_name"] == selected_stop]

    filtered_df = filtered_df[filtered_df["delay_minutes"] >= min_delay]

    st.write("Filtered predicted arrivals:")
    st.dataframe(filtered_df, use_container_width=True)

    # Chart 1: Delay by stop
    if not filtered_df.empty:
        fig_bar = px.bar(
            filtered_df,
            x="stop_name",
            y="delay_minutes",
            color="stop_name",
            title="Delay by Stop"
        )
        st.plotly_chart(fig_bar, use_container_width=True)

        # Chart 2: Planned vs Predicted time
        fig_scatter = px.scatter(
            filtered_df,
            x="planned_time",
            y="predicted_time",
            color="stop_name",
            size="delay_minutes",
            hover_data=["reason"],
            title="Planned vs Predicted Arrival Time"
        )
        st.plotly_chart(fig_scatter, use_container_width=True)
    else:
        st.warning("No data match the selected filters.")

# Section 4: Verification
st.subheader("4. Data Verification")

st.markdown("""
The displayed forms are verified against the actual MariaDB system data:
- imported row counts are shown above;
- tables are read directly from the database;
- the filtered forms display subsets of the same database records.
""")

if not predicted_arrivals.empty:
    st.write("Verification sample from predicted_arrivals:")
    st.dataframe(predicted_arrivals.head(), use_container_width=True)

st.success("Visualization platform loaded successfully.")
